ffxivcode/AutoDuty

AutoDuty/Helpers/FollowHelper.cs
Changed NPC piggybacking from W key to NavMesh. I have found very few instances where it is worse.
=> Better NPC Piggybacking

AutoDuty/AutoDuty.cs
Because Vera told me to do it.
=> Pause and Resume Commands

AutoDuty/AutoDuty.cs
Easy addition for unimplemented code.
=> Implement StopForCombat

AutoDuty/Windows/BuildTab.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/PathsTab.cs
Minor adjustments such as resizing windows & tabs and rearranging some elements to make AD more manageable.
=> Minor GUI Update

AutoDuty/Managers/TrustManager.cs, AutoDuty/Windows/MainTab.cs
Should now be working without issue/crashes for ShB through Dawntrail Trusts
=> Reenable Trust Support

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Managers/DutySupportManager.cs, AutoDuty/Managers/SquadronManager.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Windows/BuildTab.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/MiniTab.cs
Reading from the english sheets for internal logic,
while reading from the client language sheet to display the duty names.
=> Duty Language Fixes

AutoDuty/Windows/BuildTab.cs
Easier for editing, and the extra storage required is negligible.
=> pretty print json paths

AutoDuty/Windows/MainTab.cs
Readjusting the selection checkboxes back to sameline as more elements have since been added below.
=> GUI Checkbox revert

AutoDuty/AutoDuty.cs, AutoDuty/AutoDuty.csproj, AutoDuty/AutoDuty.json, AutoDuty/Helpers/ExtractHelper.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/MainWindow.cs, AutoDuty/Windows/MiniTab.cs
=> v65 - Added Auto Extract

AutoDuty/Windows/BuildTab.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/MainWindow.cs, AutoDuty/Windows/MiniTab.cs, AutoDuty/Windows/PathsTab.cs
- Resized some windows again (Trying to get a more cohesive size across tabs)
- Rearranged some elements (again)
- Sorry Herc XD
=> GUI fix(again)

AutoDuty/Managers/ActionsManager.cs
- Needed ability to attack passive npcs regardless of client localization to start combat for some dungeons. 
gac 16 = Target Next
gac 1 = Auto Attack
=> Adding ForceAttack

AutoDuty/AutoDuty.cs, AutoDuty/Windows/Config.cs
- Request by Jigain
- Adds config option to enable AutoRetainer Multi mode when looping completes.
- Should function nearly identical to AutoLogout
=> AutoRetainer Multi on Loop Completion

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/GCTurninHelper.cs, AutoDuty/Helpers/GotoBarracksHelper.cs, AutoDuty/Helpers/GotoHelper.cs, AutoDuty/Helpers/GotoInnHelper.cs
Modified GotoInn and GotoBarracks and GotoGCSupply to not use AethernetTravel.
=> Added optional bool useAthernetTravel for GotoHelper

AutoDuty/AutoDuty.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/PathsTab.cs
When Level Reaches a set Int
When No Rested XP
When an Item/Items Reachs a Set Qty
=> Implemented Loop Stopping Options:

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs
Framework for Variant Dungeons, addressing Issue #15 
(No Paths yet)
=> Variant dungeon support

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ConfigHelper.cs
/slash command:
/autoduty cfg NameOfConfig value
type
/autoduty cfg list
to see a list of configurable options
=> Implemented ability to change Config options via

AutoDuty/Managers/ActionsManager.cs
=> ForceAttackFix

AutoDuty/Helpers/ExtractHelper.cs, AutoDuty/Helpers/GCTurninHelper.cs
Added Targeting and Interacting with
Personnel Officer by DataId
=> To prevent Deliveroo Stuck

AutoDuty/Windows/Config.cs
=> AddingMissingConfigBools

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Helpers/InventoryHelper.cs, AutoDuty/Helpers/QueueHelper.cs
Fixed Queueing in ContentsFinder when
Dungeon has - in the Name (thx Dalamud)
Added Command:
/autoduty overlay ->
opens overlay window
/autoduty overlay lock ->
locks the overlay window
/autoduty overlay nobg ->
removes background from overlay window
=> Fixed Repair

AutoDuty/Managers/ActionsManager.cs
Currently causes an annoying error in the log
=> Fixed RevivalAction parameters

AutoDuty/Managers/ActionsManager.cs
Uses camera override to force an orientation for complex pathing.
=> AddCameraFacingAction

AutoDuty/AutoDuty.cs, AutoDuty/Windows/Config.cs
=> Added Config for GCTurnin:

AutoDuty/AutoDuty.cs
=> Added Command:

AutoDuty/AutoDuty.cs, AutoDuty/Windows/Config.cs
Wait time before after loop actions
=> Added Config:

AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Managers/TrustMember.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs
Adds Trust Party selection. Nuff said.
=> Trust Party Selection

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Helpers/ImGuiHelper.cs, AutoDuty/Helpers/TrustHelper.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Managers/TrustMember.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs
- Some backend improvements for future additions.
- Getting Trust member levels from the UI.
- Checking trust member levels for content availability checks.
- Coloring Trust members after roles.
=> Trust module improvements

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Helpers/ImGuiHelper.cs, AutoDuty/Helpers/TrustHelper.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Managers/TrustMember.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs
Well that was a mess to clean up the history.
Didn't get an answer on how you wanted it, so.. this.
- Some backend improvements for future additions.
- Getting Trust member levels from the UI.
- Checking trust member levels for content availability checks.
- Coloring Trust members after roles.
=> Trust improvements v2

AutoDuty/AutoDuty.cs
The unit price is low, so it should always be used during duty raids.
=> Boiled Eggs Anytime

AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Windows/MainTab.cs
Filters out trials from the Trust list, and updates the index method to be more future proof (you're welcome Vera).
=> Update Trust List and Index Method

AutoDuty/Managers/VariantManager.cs
Missed this step due to yesalreadys autoconfirm option
Adding at a users request
=> AddConfirmPressToVarManager

AutoDuty/AutoDuty.cs
=> Fixed AutoEgg + Repair case

AutoDuty/AutoDuty.cs
/autoduty run TerritoryTypeInteger LoopTimesInteger
- starts auto duty in the TerritoryType specified for the looptimes specified /autoduty tt name of duty
- logs and copies to clipboard the TerritoryTypeInteger of the "name of duty"
=> Added Commands:

AutoDuty/Windows/MainTab.cs
You can change it if you want I was feeling sassy
=> EditDoHoLMessage

AutoDuty/Windows/MainTab.cs
Added check to see if player is available before trying to load the list Otherwise window would break on title screen when using the new "Show Main Window On Start Up" config
Cleaned up DoH/Blue Message slightly
=> DoH+Main on Start Fix

AutoDuty/Managers/ActionsManager.cs
Only completes the interactable step once the target goes untargetable. Will loop in case of interruptions.
Closes #235
=> Interact loop if failed

AutoDuty/AutoDuty.cs, AutoDuty/Data/Enum.cs, AutoDuty/Helpers/AMHelper.cs, AutoDuty/Helpers/AutoEquipHelper.cs, AutoDuty/Helpers/AutoRetainerHelper.cs, AutoDuty/Helpers/DesynthHelper.cs, AutoDuty/Helpers/ExitDutyHelper.cs, AutoDuty/Helpers/ExtractHelper.cs, AutoDuty/Helpers/GCTurninHelper.cs, AutoDuty/Helpers/GotoBarracksHelper.cs, AutoDuty/Helpers/GotoHelper.cs, AutoDuty/Helpers/GotoHousingHelper.cs, AutoDuty/Helpers/GotoInnHelper.cs, AutoDuty/Helpers/MapHelper.cs, AutoDuty/Helpers/QueueHelper.cs, AutoDuty/Helpers/RepairHelper.cs, AutoDuty/Managers/ContentPathsManager.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/MainWindow.cs, AutoDuty/Windows/Overlay.cs
Attempted a fix for when stopping a duty and restarting 
and then finishing and going into a duty manually it insta 
exiting the duty
Cleaned up some code
Added States Flag
Changed Started and Running to States:
Started = Navigating
Running = Looping
Added Stop of ExitDutyHelper to StopAndResetAll
Removed Extra Location from Limsa GotoInn
Added Stop RSR to StopAndResetAll
=> 257 exitduty helper misbehaving

AutoDuty/Helpers/InventoryHelper.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainWindow.cs
Addresses #233
And adds an overload method for CanRepair for button use
=> Overlay button disables

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/GCTurninHelper.cs, AutoDuty/Windows/Config.cs
=> Added Config for GC Turnin:

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Helpers/QueueHelper.cs, AutoDuty/Managers/ContentPathsManager.cs, AutoDuty/Managers/DutySupportManager.cs, AutoDuty/Managers/SquadronManager.cs, AutoDuty/Managers/TrustManager.cs, AutoDuty/Windows/BuildTab.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/MainWindow.cs, AutoDuty/Windows/Overlay.cs, AutoDuty/Windows/PathsTab.cs
- Fixes queuing for regular duty finder content for non-English game clients.
- Update the UI to be resizable with various elements updated to be reactive to window size.
=> Client Language fixes & UI Updates

AutoDuty/Helpers/GotoHousingHelper.cs, AutoDuty/Helpers/MovementHelper.cs, AutoDuty/Windows/Config.cs
PersonalHomeEntrancePath
FCEstateEntrancePath
=> Added Configs:

AutoDuty/Helpers/DesynthHelper.cs, AutoDuty/Windows/Config.cs
- Only Skill Ups -- when this option is selected you can also select Auto GC Turnin
=> Added Config to Auto Desynth:

AutoDuty/AutoDuty.cs, AutoDuty/Data/Enums.cs, AutoDuty/Data/Extensions.cs, AutoDuty/Helpers/AMHelper.cs, AutoDuty/Helpers/AutoEquipHelper.cs, AutoDuty/Helpers/AutoRetainerHelper.cs, AutoDuty/Helpers/DesynthHelper.cs, AutoDuty/Helpers/ExitDutyHelper.cs, AutoDuty/Helpers/ExtractHelper.cs, AutoDuty/Helpers/GCTurninHelper.cs, AutoDuty/Helpers/GotoBarracksHelper.cs, AutoDuty/Helpers/GotoHelper.cs, AutoDuty/Helpers/GotoHousingHelper.cs, AutoDuty/Helpers/GotoInnHelper.cs, AutoDuty/Helpers/MapHelper.cs, AutoDuty/Helpers/QueueHelper.cs, AutoDuty/Helpers/ReflectionHelper.cs, AutoDuty/Helpers/RepairHelper.cs, AutoDuty/Helpers/SoundHelper.cs, AutoDuty/IPC/IPCProvider.cs, AutoDuty/Managers/ActionsManager.cs, AutoDuty/Windows/Config.cs, AutoDuty/Windows/MainTab.cs, AutoDuty/Windows/MainWindow.cs, AutoDuty/Windows/Overlay.cs
Fixed Interact to be More Reliable on GettingGameObject if InCombat
Fixed Interact to be More Reliable when SelectYesno and Talk Addons are present 
Fixed Pause State to pause more things (Hopefully ALL)
Various Code Cleanup
Various UI Modifications
Added (Optional) BareMode to Run /command and IPC
- This will turn off all Pre, Between and Termination Loop Actions
- Defaults to False
=> Lots of Changes

AutoDuty/AutoDuty.cs, AutoDuty/IPC/IPCSubscriber.cs
Added BMR and VBM versions to EnabledCheck
=> Added IPC for Version

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/AMHelper.cs, AutoDuty/Helpers/AutoEquipHelper.cs
=> Refactored AutoEquipHelper

AutoDuty/Managers/ActionsManager.cs
ModifyIndex
- Changes the current index of the path and starts from there 
- ConditionAction
-- Allows for checking a condition and Invoking an Action if true 
--- ex ConditionAction|0, 0 ,0|Item;4056,ModifyIndex;2 --- This will check your inventory for item 4056 and if it exists it will modify the index of the path to 2
=> Added Actions:

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/ISSUE_TEMPLATE/config.yml
- Created 2 issue template forms
- Added a config that prevents creating custom issues
=> Add issue templates

AutoDuty/AutoDuty.cs, AutoDuty/Managers/ActionsManager.cs
=> Fixed a bug that would not loop if Between Loop Actions was not enabled

.github/ISSUE_TEMPLATE/1-bug-report.yml
- Added version number since you ask that every time someone has an issue 😄
=> Add version number to bug report issue template

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml
=> Add "unconfirmed" to default issue labels

AutoDuty/AutoDuty.cs
Fixing the current issue on load.
Also issue https://github.com/ffxivcode/AutoDuty/issues/395
=> Check if player is loaded before directly accessing

AutoDuty/AutoDuty.cs, AutoDuty/Managers/ActionsManager.cs, AutoDuty/Paths/(1041) Brayflox's Longstop.json, AutoDuty/Paths/(1042) The Stone Vigil.json
Added More ConditionAction Conditions
=> Added ConditionAction to Stone Vigil

AutoDuty/Managers/ActionsManager.cs, AutoDuty/Paths/(580) Alexander - The Eyes of the Creator.json, AutoDuty/Paths/(584) Alexander - The Eyes of the Creator (Savage).json
Added WaitFor:
ConditionFlag
usage: ConditionFlag;FlagName;false
-- FlagName is Dalamud Condition Flag such as Jumping61 or BetweenAreas 
--- Example: WaitFor|0, 0, 0|ConditionFlag;Jumping61;false 
Modified Paths:
(580) Alexander - The Eyes of the Creator
(580) Alexander - The Eyes of the Creator (Savage)
=> Modified Boss TreasureScan to 50

AutoDuty/AutoDuty.cs, AutoDuty/AutoDuty.csproj
=> Special Interactables Implementation

AutoDuty/Helpers/LevelingHelper.cs
- Requires https://github.com/awgil/ffxiv_bossmod/pull/490
=> Adding L69

AutoDuty/Helpers/ContentHelper.cs
Also fixes https://github.com/ffxivcode/AutoDuty/issues/482
=> Duty Names pulled with special characters to allow queueing

AutoDuty/Windows/MainTab.cs
fix the restrictions for blue mage
=> Blue mage restrictions fix

AutoDuty/Data/Classes.cs, AutoDuty/Helpers/ContentHelper.cs, AutoDuty/Helpers/TrustHelper.cs, AutoDuty/Windows/MainTab.cs
general trust improvements, commit messages give the highlights.
=> Trust improvements

AutoDuty/Helpers/ContentHelper.cs
CN doesn't have the english sheet apparently
=> only grabbing english contentfinder if english sheet is available

AutoDuty/Paths/(142) The Dragon's Neck.json, AutoDuty/Paths/(295) The Bowl of Embers (Extreme).json, AutoDuty/Paths/(296) The Navel (Extreme).json, AutoDuty/Paths/(297) The Howling Eye (Extreme).json, AutoDuty/Paths/(359) The Whorleater (Extreme).json, AutoDuty/Paths/(364) Thornmarch (Extreme).json, AutoDuty/Paths/(366) Battle on the Big Bridge.json, AutoDuty/Paths/(368) A Relic Reborn the Chimera.json, AutoDuty/Paths/(369) A Relic Reborn the Hydra.json, AutoDuty/Paths/(375) The Striking Tree (Extreme).json, AutoDuty/Paths/(396) Battle in the Big Keep.json, AutoDuty/Paths/(426) The Chrysalis.json, AutoDuty/Paths/(430) The Fractal Continuum.json, AutoDuty/Paths/(437) The Singularity Reactor.json, AutoDuty/Paths/(446) Thok ast Thok (Extreme).json, AutoDuty/Paths/(447) The Limitless Blue (Extreme).json, AutoDuty/Paths/(448) The Minstrel's Ballad Thordan's Reign.json, AutoDuty/Paths/(524) Containment Bay S1T7 (Extreme).json, AutoDuty/Paths/(566) The Minstrel's Ballad Nidhogg's Rage.json, AutoDuty/Paths/(577) Containment Bay P1T6 (Extreme).json
mainly for wondrous tails automation
=> adding old trials + fractal continuum

AutoDuty/AutoDuty.cs
=> Wait Time between loops Fix

AutoDuty/AutoDuty.cs
=> Added check for Arguments.Count > 0

AutoDuty/Helpers/QueueHelper.cs
=> Remove-Italics-/Italics-tags-from-Duty-Names

AutoDuty/Windows/Config.cs
- [only show preferred repair npc if not self repairing](https://github.com/ffxivcode/AutoDuty/commit/36ec9f499da74340bae876e7c09e4f0f3a05cb44)
- [GC turn in and desynth in column matrix](https://github.com/ffxivcode/AutoDuty/commit/6bc3654e3b639171548dab2d135fa33737d934c8)
- [added colon in config for commands only when checked](https://github.com/ffxivcode/AutoDuty/commit/308ef75a054fb1d034fdc32529ca24ed7d6e664b)
=> slight Config tab changes

AutoDuty/Data/Classes.cs, AutoDuty/Helpers/TrustHelper.cs
Apparently G'raha has an unlock quest in 5.3 for trust...
=> Adding TrustMember unlock quest id

AutoDuty/Helpers/PlayerHelper.cs, AutoDuty/Helpers/TrustHelper.cs, AutoDuty/Paths/(1193) 「Testing」 Worqor Zormor.json, AutoDuty/Windows/BuildTab.cs
Using Navigation and IsReady checks instead of AutoMove and Wait
=> Worqor test path

AutoDuty/AutoDuty.cs, AutoDuty/IPC/IPCSubscriber.cs, AutoDuty/Managers/ActionsManager.cs
- [StopForCombat dis/enables AI and waits shortly](https://github.com/ffxivcode/AutoDuty/commit/9555892519bd06fa079a5ee2bae69c847fff7a68)
- [adjusted vbm commands to current update](https://github.com/ffxivcode/AutoDuty/commit/fc55b4cb6ed334e01b26f3a14fc28d13b078bf7a)
- Adjusted Prae specific code for stability
- [Added Prae Duty specific code 3 for gaius fight](https://github.com/ffxivcode/AutoDuty/commit/a9d92c7305fb219bfcd44c2590374ea68d18815f)
- [Add mounted check to prae action cannon](https://github.com/ffxivcode/AutoDuty/commit/0c1f2038c5e0a3fbbc69cf6349c5d4dacf3a0971)
- [Prae specific delegate adjusted to be nulled on duty switch](https://github.com/ffxivcode/AutoDuty/commit/b37dd26d1543d20ea1a96b9f97999c91c5d71725)
=> StopForCombat + vbm adjustments + Prae stability

AutoDuty/Paths/(933) Matoya's Relict.json
=> Update (933) Matoya's Relict.json

AutoDuty/Paths/(743) the Fractal Continuum (Hard).json
Added the path for “(743) the Fractal Continuum (Hard).”
=> Update (743) the Fractal Continuum (Hard).json

AutoDuty/Helpers/RepairHelper.cs
=> stopping city repair if running and in a duty with path

AutoDuty/Managers/ActionsManager.cs
- [ConditionAction fixed boxing issue](https://github.com/ffxivcode/AutoDuty/commit/508e255e65cbde81ff06f3c2cd60dc9819d9c018)
- [ConditionalAction ItemCount Index fix](https://github.com/ffxivcode/AutoDuty/commit/d65d5e23d82c95c0640666068460493d8db3305c)
=> Fix item count

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/MapHelper.cs, AutoDuty/Helpers/QueueHelper.cs
[minor logic issue with versioning](https://github.com/ffxivcode/AutoDuty/commit/131925511f63f49933437296b94fb0b545868432)
[duty support queue for sidequests fix](https://github.com/ffxivcode/AutoDuty/commit/ea818fca5658b0e233f98babf6cc2089f0cbbcf7)
=> sidequest duty support fix

AutoDuty/Paths/(1111) The Antitower.json
The final boss of Antitower is technically two bosses with a phase change in the middle. Sometimes AutoDuty will leave duty in the middle of the phase change.
=> update antitower final boss

AutoDuty/Helpers/ReflectionHelper.cs, AutoDuty/IPC/IPCSubscriber.cs
=> BMR range check before set

AutoDuty/Paths/(188) The Wanderer's Palace (Hard).json, AutoDuty/Paths/(189) Amdapor Keep (Hard).json, AutoDuty/Paths/(387) Sastasha (Hard).json
fixed interactables on
188 wandering palace hard.
189 amdapor keep hard.
387 sastasha hard.
=> fixed interactables 

AutoDuty/Paths/(188) The Wanderer's Palace (Hard).json
added a node with stop for combat = true fixing some classes skipping ahead before killing the flags and getting stuck.
primarily melee classes afaik.
=> added one node fixing mechanic issue for some classes.

AutoDuty/(443) Alexander - the Cuff of the father.json, AutoDuty/Paths/(442) Alexander - The Fist of the Father.json, AutoDuty/Paths/(450) Alexander - The Cuff of the Father (Savage).json, AutoDuty/Paths/(451) Alexander - The arm of the Father (Savage).json, AutoDuty/Paths/(523) Alexander - The Burden of the Son.json
added /vnav rebuild to fist of the father due to the maze route changing causing vnav issues.
and made a route for cuff of the father.
=> fix for alexander fist of the father and new route for cuff of the father

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/ConfigHelper.cs, AutoDuty/Helpers/RegExHelper.cs
Mainly allowed cfg command editing of IList configs
=> cfg adjustments

AutoDuty/AutoDuty.cs, AutoDuty/Managers/ContentPathsManager.cs, AutoDuty/Windows/MainTab.cs
[Loading correct path on duty load](https://github.com/ffxivcode/AutoDuty/commit/a8330b4c00c4aecd7b33c7550ffdae191fc8e04a)
[align vnav mesh progress bar in same line](https://github.com/ffxivcode/AutoDuty/commit/1787f69cf890a293dd53ad17bd8c6f7c00796abb)
=> UX path loading improvements

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/MovementHelper.cs, AutoDuty/IPC/IPCSubscriber.cs, AutoDuty/Windows/Config.cs
[Double check Wrath job setup](https://github.com/ffxivcode/AutoDuty/commit/8c643d4074a8ecb0dc4a36306dbce02146a8db1c)
[added option to rebuild navmesh on first dungeon load](https://github.com/ffxivcode/AutoDuty/commit/12a87a95b66e99d2f0f1eabf2653bbf445fbfdf4)
[automove off when moving](https://github.com/ffxivcode/AutoDuty/commit/e5e7b1b9ca1c66e0800576d4f87811d99940b70a)
=> Various Run stability improvements

AutoDuty/Paths/(581) Alexander - The Breath of the Creator.json
made basic path while doing tails book.
=> Alexander - breath of the creator path

AutoDuty/Paths/(938) Paglth'an.json
Fixed the waiting time after the Dragons
=> Update (938) Paglth'an.json

AutoDuty/Helpers/QueueHelper.cs
To ensure server is not spammed with requests
=> Add a delay between repeating register for duty button click

AutoDuty/Managers/ActionsManager.cs, AutoDuty/Paths/(1176) Aloalo Island - Path 1.json, AutoDuty/Paths/(1176) Aloalo Island - Path 2.json, AutoDuty/Paths/(1176) Aloalo Island - Path 3.json, AutoDuty/Paths/(1176) Aloalo Island - Path 4.json
adds support for select string and paths 1-4 of aloalo variant dungeon
=> Aloalo support

AutoDuty/Helpers/GotoHousingHelper.cs
FC estates can be remodelled too apparently
=> adjusted goto housing checks

AutoDuty/Paths/(1040) Haukke Manor.json, AutoDuty/Paths/(1266) The Underkeep.json
fix haukke manor getting stuck on boss 2 loot and underkeep trying to walk up the pipe that falls after boss 1.
=> Path updates

AutoDuty/Resources/AutoDuty.json, AutoDuty/Resources/AutoDuty_Passive.json
This reverts commit 448f0628010ac5fc0e3b6bb66f7ee443686baf30.
=> Revert temporary vbm preset adjustment. Bug believed to be fixed.

AutoDuty/Windows/MainTab.cs
Shows the dungeon level in the list so I don't have to check so many menus when khloe asks me to run certain level ranges because I don't have them all memorized!
=> Show dungeon level in dungeon list

AutoDuty/AutoDuty.cs, AutoDuty/Helpers/CofferHelper.cs, AutoDuty/Windows/Config.cs
=> Added additional logging to coffer helper

AutoDuty/Helpers/AutoEquipHelper.cs, AutoDuty/Windows/BuildTab.cs
https://github.com/ffxivcode/AutoDuty/pull/964
=> PR adjustments for 964

AutoDuty/AutoDuty.cs, AutoDuty/Windows/Overlay.cs
=> restore /ad overlay

(1200) Everkeep.json
=> Add path for everkeep

AutoDuty/AutoDuty.cs
=> Termination Options Kill Client and Kill PC enqeued

AutoDuty/Managers/ActionsManager.cs
This is needed for sildin subterane path to tell which direction nanamo turns after the first boss which allows branching to whichever path is open.
path PR comming as soon as I manage to test both forks
=> condition action for object to point distance

AutoDuty/Managers/ActionsManager.cs, AutoDuty/Paths/(1069) The Sil'dihn Subterrane - Exit 4 - Left.json
this is just for the path, review/merge the other one first and I hope it cleans up the duplicate commits properly
=> sildihn path 4

AutoDuty/Paths/(195) The Final Coil of Bahamut - Turn 3.json
This just walks up to the boss for turn 3 which is good enough to unsync it for WT Final coils entry
=> Path for final coil turn 3

AutoDuty/Paths/(750) Sigmascape V3.0.json, AutoDuty/Paths/(943) Eden's Promise Litany.json
A couple more raids that BMR handles well enough to include in my WT script.
Just a boss step and let BMR handle it.
=> More raid duties for WT support

AutoDuty/Paths/(519) The Lost City of Amdapor (Hard).json
added treasure chests and final boss chest
=> Amdapor (Hard) added treasure chests and boss chest

AutoDuty/Paths/(663) The Temple of the Fist.json
only tested unsync but don't see too much issue apart from the knockback traps on some paths if the AI doesn't avoid them.
=> added temple of the fist path

AutoDuty/Paths/(1111) The Antitower.json
Fixed pathing to enter doors/teleporters, added move to final boss chest and interact with exit.
=> Update (1111) The Antitower.json

AutoDuty/Paths/(1040) Haukke Manor.json, AutoDuty/Paths/(172) The Aurum Vale.json
=> 172 Aurum Vale - added treasure chests
