ffxivcode/AutoDuty

AutoDuty/IPC/IPCSubscriber.cs

The IsEnabled condition in the IPCSubscriber class was updated to check for both "BossMod" and "BossModReborn". This will allow the program to function correctly if either service is ready and available.

Update IsEnabled condition in IPCSubscriber

---

AutoDuty/AutoDuty.cs

Adding command to ensure that vnav aligncamera is enabled as it is required for most paths.

Aligncamera Initialization

---

AutoDuty/AutoDuty.cs

When AutoDuty stops, the BossMod AI stays on, which is quite annoying because it does some weird stuff when playing normally.
We should turn it back off once we're done with AutoDuty.

Turn off BossMod AI when stopping

---

AutoDuty/Helpers/ContentHelper.cs
AutoDuty/Managers/DutySupportManager.cs

This change should fix the indexing issues on older dungeons caused by unlocking the dawntrail expack category when you get your first dawntrail dungeon.
I still don't know why dawntrail dungeons won't even open the gui

Index ARR/HW/SB Dungeons Properly

---

AutoDuty/Helpers/ObjectHelper.cs
AutoDuty/IPC/IPCSubscriber.cs
AutoDuty/Managers/ActionsManager.cs

The current HasModule implementation of Bossmod has some problems, since Dalamud can't serialize the boss IGameObjects.
See https://github.com/awgil/ffxiv_bossmod/pull/377 for more info.
This fixes the constant errors that the current HasModule method throws.

Use Bossmod's new HasModuleByDataId IPC instead

---

AutoDuty/Helpers/FollowHelper.cs

After applying the fix (https://github.com/ffxivcode/AutoDuty/pull/53) about errors from Bossmod's HasModule method, AutoDuty stops working after every boss encounter.
This fixes the problem by ensuring that the FollowHelper's FollowUpdate method is only added to the Framework Update event once and doesn't continue to run when the boss is dead.

Fix FollowHelper Update being called even when disabled

---

AutoDuty/Managers/SquadronManager.cs

Updated Squadron Manager with revised checks for opening the squadron duty finder. Currently enables you to loop squadron missions as needed. Tested a few times and seems stable.

Fix Squadron Mission Loop

---

AutoDuty/Managers/ActionsManager.cs

Triggers the `/automove on` chatcommand, and after specified time `/automove off`.
This prevents the hassle of adding the 3 commands individually.

added AutomoveFor action

---

AutoDuty/Managers/ActionsManager.cs

- Added commands to toggle bmr followtarget alongside StopForCombat steps as leaving enabled would break the action.

StopForCombatFix

---

AutoDuty/AutoDuty.cs

'Shortcut' was changed to ‘2000700’.
This will probably work in all languages.

Shortcut >> 2000700

---

AutoDuty/Managers/RegularDutyManager.cs

Very minor adjustment to introduce a greater delay between opening the DF window and queueing for a dungeon - Likely just a temporary fix but felt more reliable.

RegularDutyMiniFix

---

AutoDuty/AutoDuty.cs
AutoDuty/Windows/Config.cs
AutoDuty/Windows/MainTab.cs

Adds an option to disable Rotation Solver as being mandatory for the plugin in favour of using another rotation plugin.

Alternative Rotation Plugin setting

---

AutoDuty/AutoDuty.cs

This disables the VBM/BMR AI when "Stop" is pressed in the UI.

Disable bossmod AI when AutoDuty is stopped prematurely

---

AutoDuty/Paths/(1110) The Aetherochemical Research Facility.json

When entering the last boss room of ARF, the script will sometime back out of the room and stop working properly.
This seems to fix this behavior. From what I can infer the number at the end of the path adds a wait period which seems to add tolerance for the loading screen (which I assume is causing the issue).
There's another issue in ARF pathing that would be nice to add some tolerance for but I'm not sure how to go about it. Before the second boss there are two orbs that needs to be forced attack (since they're not aggressive) to open up the path forward. The script sometimes pass them by without attacking them. It could be more likely on casters but I'm not sure.

add tolerance for last boss room loading in ARF

---

AutoDuty/Paths/(1110) The Aetherochemical Research Facility.json

Figured out the source of the bug in elevator in ARF and don't know why it didn't occur to me sooner.
The cause was the same as the last boss room bug : the loading screen being longer than expected.
So, just like with the last boss room problem I made the previous automovefor command longer which as mentioned previously should act as wait for the next command to add some tolerance for the loading screen.
I wonder if it'd be possible for the mod as a whole to detect loading screens and to avoid moving to the next command as long as it is in a loading screen so as to generalize the fix.

add some tolerance for elevator room loading screen in ARF

---

AutoDuty/AutoDuty.cs
AutoDuty/Helpers/AutoEquipHelper.cs
AutoDuty/Windows/MainTab.cs

-Removal of Taskmanager requirement from AutoEquipHelper
-Reorganized process to save gearsets only after equipping new gear
-Added functionality to leveling checkbox, when enabled, if AutoEquip is true, will use best available gear PRIOR to searching for appropriate leveling dungeon

Auto Equip Fixes

---

AutoDuty/AutoDuty.cs
AutoDuty/Paths/(1043) Castrum Meridianum.json
AutoDuty/Paths/(1113) Xelphatol.json
AutoDuty/Paths/(1114) Baelsar's Wall.json
AutoDuty/Windows/Config.cs

Fixing termination dropdown by giving it a unique identifier
Added termination mode "Kill PC" to shutdown the PC after 20s. Enabled for Windows and Linux.
Auto Repair options streamlined to not go into invalid cases seemingly. Removed internal repair with city npc, as it is unused.
Added Show Main Tab on startup option.
Minor syntax fixes for 3 paths.
Enabling Scheduler again.

Config options

---

AutoDuty/Helpers/LevelingHelper.cs
AutoDuty/Managers/TrustManager.cs
AutoDuty/Windows/MainTab.cs

- Trust not blocked when not all members are available yet
- trust group resetting if selected duty is too high
- MainTab trust member refresh without member list visible

Trust level fixes

---

AutoDuty/Windows/Config.cs

Changing the initial state of "Loot Boss Treasure Only" to false on fresh configs

ChangedInitStateOfBossLoot

---

AutoDuty/Managers/ActionsManager.cs

No longer loops if you're between areas (i.e used a teleporter) or if the object isn't an event object (such as NPCs)

Interact Loop Issue Fix

---

AutoDuty/AutoDuty.cs
AutoDuty/Managers/ActionsManager.cs
AutoDuty/Windows/Config.cs
AutoDuty/Windows/MainTab.cs
AutoDuty/Windows/MainWindow.cs

Auto Manage Vnav Align Camera
- Turns on Align Camera at the start of navigation and if it was off to begin with will turn it back off at the end of loops or on Stop Modified AutoMoveFor to now set Movement Mode to Standard (if it wasnt already) and back(if it was Legacy)

Added Config:

---

AutoDuty/AutoDuty.cs

hello, please review the following:
when reviving then taking shortcut, Condition_ConditionChange will cause Indexer++ skipping the actual step the player was on. 
~~the following adds a _recentlyRevived which is set in OnRevive and is removed after 14 seconds. the conditionChange during the shortcut transition ignores the transition~~
the following adds a Stage != Stage.Revived check to Condition_ConditionChange to prevent the Indexer increment*
issue was identified in Stone Vigil after dying to Boss 2. A death during Boss 1 did not cause the issue due to no shortcut being present upon revive

fix indexer iterating during conditionchange after revive

---

AutoDuty/AutoDuty.cs
AutoDuty/Data/Enum.cs
AutoDuty/Helpers/AMHelper.cs
AutoDuty/Helpers/DesynthHelper.cs
AutoDuty/Helpers/ExitDutyHelper.cs
AutoDuty/Helpers/ExtractHelper.cs
AutoDuty/Helpers/GCTurninHelper.cs
AutoDuty/Helpers/GotoBarracksHelper.cs
AutoDuty/Helpers/GotoHelper.cs
AutoDuty/Helpers/GotoHousingHelper.cs
AutoDuty/Helpers/GotoInnHelper.cs
AutoDuty/Helpers/MapHelper.cs
AutoDuty/Helpers/ReflectionHelper.cs
AutoDuty/Helpers/RepairHelper.cs
AutoDuty/Helpers/TeleportHelper.cs
AutoDuty/IPC/IPCSubscriber.cs
AutoDuty/Managers/ActionsManager.cs
AutoDuty/Windows/MainTab.cs
AutoDuty/Windows/Overlay.cs

- Rotation Solver Reborn will now check if in the State
- Before changing it. Readded Rotation State Setting to:
- Stage.Moving InCombat Detection
- Stage.Action Invoke AutoDuty will now check the states of:
Pandora - Auto-interact with Objects in Instances
YesAlready
and disable both on start of loops, and other actions and reenable if applicable at the end of loops or stop Fixed a bug that was not showing Overlay at times.

Modified Rotation State Setting:

---

AutoDuty/AutoDuty.cs

After defeating the final boss and having "Disable automatically during cutscenes." enabled in RSR, you'll get spammed with RSR enabling and disabling:
This happens because AutoDuty keeps trying to enable RSR and RSR keeps trying to disable during a cutscene.
The fix is using the same condition that [RSR uses to disable itself](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/blob/2e1ccb9456f5242548e1b99a2361809d10ede064/RotationSolver/Commands/RSCommands_Actions.cs#L168).

Fix RSR reenabling during cutscenes

---

AutoDuty/AutoDuty.cs
AutoDuty/AutoDuty.csproj
AutoDuty/Data/Enum.cs
AutoDuty/Helpers/SoundHelper.cs
AutoDuty/Paths/(1047) The Howling Eye.json
AutoDuty/Windows/Config.cs
AutoDuty/packages.lock.json

Added end of loop audio configuration.
Supports in-game sounds for the average user. Limitation of in-game sounds is that they play on the System Sounds channel. 
As an alternative so that sounds still play when you have the Master/SystemSounds muted, I added NAudio with the option to enter a custom sound file path. These sounds will play even when you have the prior sound channels muted in game. 
(Also sneaking in a Howling Eye path for Questionable future use)

End Of Loop Audio

---

AutoDuty/AutoDuty.cs
AutoDuty/Helpers/ImGuiHelper.cs
AutoDuty/Helpers/LevelingHelper.cs
AutoDuty/Helpers/ObjectHelper.cs
AutoDuty/Helpers/TrustHelper.cs
AutoDuty/Managers/TrustManager.cs
AutoDuty/Managers/TrustMember.cs
AutoDuty/Windows/MainTab.cs

- Trust members are initialized with their starting level.
- Trust member level is displayed as greenish if they are at cap
- Trust member selection is not locked during leveling, if all members are at cap.

Trust updates

---

AutoDuty/AutoDuty.cs
AutoDuty/Data/Enum.cs
AutoDuty/Windows/Config.cs

There was a request in the Jp community to cut off other plugins to start the loop. For example, those that log Splatoon, ARR, Lemegeton, etc. To turn these off all at once, before and after the start and after the completion of all loops, would be a great feature. It would be useful to be able to type a command (macro?) starting and completion of all loops to turn them off all at once.
Changes
- Added command at the start and at the completion of a loop
- Added command settings to config
(Translated by DeepL)

Added command at the start and at the completion of a loop

---

.github/workflows/publish.yml

- Uses the "on release" action trigger instead of checking for new tags
- Removes the step to get current tag since that's available as `github.ref_name` already
- Removed extra echos and last step entirely
- Added pushing the release body to changelog for plugin
Ignore the double commits, I had to rebase to get my commit signing to work since it somehow broke between yesterday and today.

Update GitHub action

---

AutoDuty/Paths/(170) Cutter's Cry.json

See title. Tested on every role 5x times without issues, but may need to readjust first and second room later depending on where the mobs spawn after the first wave is killed. Aside from that, I haven't noticed any nav issues after those two rooms.

Add Cutter's Cry Dungeon

---

AutoDuty/AutoDuty.cs
AutoDuty/Data/Classes.cs
AutoDuty/Helpers/LevelingHelper.cs
AutoDuty/Helpers/PlayerHelper.cs
AutoDuty/Helpers/TrustHelper.cs
AutoDuty/Windows/MainTab.cs

Fixed an issue where Leveling Mode would not Check Trust member levels when you only have the 1st Dungeon in any xpac unlocked
Trust Leveling Mode will now turn off on Class Change 
Trust Leveling Mode will now turn off if your iLevel becomes lower than 370 
Support Leveling Mode will now Rechoose the Duty on iLevel Change 
Added a TON of Debug logging to Leveling Mode

Fixed issues in Leveling Mode

---

AutoDuty/AutoDuty.cs
AutoDuty/Data/Classes.cs
AutoDuty/Data/Enums.cs
AutoDuty/Helpers/ContentHelper.cs
AutoDuty/Helpers/TrustHelper.cs
AutoDuty/Windows/MainTab.cs

Added DutyMode as First Argument to /ad run command
DutyMode's are the same as listed in the DropDown in MainTab
Added Error checking for every conceivable error to /ad Run Command

Fixed a bug that would let you *TRY* (and sometimes crash) entering an incompatible TT for DutyMode in /ad run command

---

AutoDuty/Helpers/ContentHelper.cs

Restores old DawnIndex, and therefore works below level 70 again.
Seems to fix https://github.com/ffxivcode/AutoDuty/issues/420 too

DawnIndex fix

---

AutoDuty/Paths/(933) Matoya's Relict.json

changed interactable "Fiery Portal" argument from name to ID

Update (933) Matoya's Relict.json

---

AutoDuty/IPC/IPCSubscriber.cs

Currently, passing the enums as is will change the wrong setting as enums are number values behind the scenes, and not strings. So for example, in current version of AD the `Lowest_Current` DPSRotationMode would be passed as `1` due to being the second item in the enumeration. However on the Wrath side, the value `1` corresponds to `Highest_Max`, so that's what it gets changed to (even if the UI shows otherwise, that's something I'm addressing that side).
Going forward it will be safer to push enums with their corresponding values on the Wrath side, which will normally be an index value (unless an item is removed however I am making similar changes to Wrath to put their values in to prevent breaks like this).
If this is merged and released before next Wrath update, the Wrath UI will show …

Update Wrath IPC to correct Enums

---

AutoDuty/Helpers/ConfigHelper.cs
AutoDuty/IPC/IPCProvider.cs

- [fix IPC run parameter assignment](https://github.com/ffxivcode/AutoDuty/commit/06c790c7d0dbc4e746d1dbbc4a0259361e4ec7e5)
- [add trust member cfg command](https://github.com/ffxivcode/AutoDuty/commit/82f1adda94cc0cdc20839fd7303f4984a7e4fb19)

IPC and cfg fix

---

AutoDuty/Helpers/ExtractHelper.cs

german apparently puts a space in there... for some reason

fix extract progress check

---

AutoDuty/Paths/(1267) The Sunken Temple of Qarn.json

Now that Sunken Temple of Qarn has been reworked for Duty Support, the problematic heads & pressure plates are no longer an issue, which makes this path SUPER simple. I added some pathing points right in front of each pressure plate though to ensure combat is encountered with the heads that must be killed.
Boss fights work flawlessly.
Simple path that I believe (no issues in my testing whatsoever) should be added to the AutoLevel list to bridge that gap after TamTara Deep Croft (Haukke is still an issue though, I'm working on ironing it out though).

Add Path: (1267) The Sunken Temple of Qarn

---

AutoDuty/Helpers/DesynthHelper.cs
AutoDuty/Windows/Config.cs

As your desynthesis skill gets closer to the current item level cap (iLevel + 50), each desynthesis grants progressively less experience. This can lead to inefficient use of items once you’re close to the cap. By letting users set a maximum skill‐up limit, we avoid inefficient desynthesis XP gains and make better use of item drops when levelling desynthesis.
**Changes:**
- Introduced a new "Item Level Limit" setting under "Only Skill Ups" in AutoDuty’s config UI.
- When your desynthesis skill >= (iLevel + Limit), AutoDuty will skip further desynthesis of that item.
- Default limit is 50 (matches current behaviour), users can decrease down to 0.

Add configurable desynth skill-up limit

---

AutoDuty/Managers/ActionsManager.cs

setting player target to be the boss npc on a boss action makes it so that bosses who do not "aggro" onto the player by distance are handled. (eg: A9S)

Set player target to be boss npc in Boss action

---

AutoDuty/IPC/IPCProvider.cs

Change the dictionary the IPC is checking from the content helper dictionary to the path manager dictionary.
The content helper dict seems to contain all content regardless if it has a path or not.

Make content has path IPC check for path not for content

---

AutoDuty/Paths/(244) The Binding Coil of Bahamut - Turn 4.json
AutoDuty/Paths/(349) Copperbell Mines (Hard).json
AutoDuty/Paths/(361) Hullbreaker Isle.json

Hullbreaker Isla path broke in the part where you have to kill some mimics and pick up the stone tablets they drop, AD wouldn't pick up the second set of tablets and would get stuck there. Poking around with it I found out that the path seemingly had the wrong tablet IDs, so I redid the whole part (and deleted a bunch of redundant/unnecessary steps).
In Copperbell MInes Hard, AD would get stuck right at the start because it would activate the lift, then run out of it before the door closed; I finally noticed the issue was that the Wait command after the lever had the wrong coordinates.
Binding Coils T4 got stuck right at the start with the Silent Terminal missing ID, redid that step.

Fixed issues in Hullbreaker Isle, Copperbell Mines (Hard), and Binding Coils T4
